spring:
#  i18n资源文件配置
   messages:
      basename: i18n/base/messages,i18n/main/messages,i18n/nettyserver/messages
      encoding: UTF-8
      cache-duration: -1

netty:
   http:
      servers[0]:
         id: test
         port: 4444