spring:
#  i18n资源文件配置
   messages:
      basename: i18n/base/messages,i18n/main/messages,i18n/nettyserver/messages
      encoding: UTF-8
      cache-duration: -1

server:
   gb32960:
      port: 6666
